### ISSUE TITLE
Unexpected crashes

### ISSUE THREAD

**Issue by Vladimirmlnkv** [videosdk-live/videosdk-rtc-ios-sdk-example#12]
Sdk version 1.2.9. 

1. Leave meeting from first app(meeting?.leave()). Second app again gets crash
<img width="1184" alt="Screenshot 2022-05-23 at 14 44 37" src="https://user-images.githubusercontent.com/7062194/169803053-51dc79be-bc01-4567-9350-8fe3832b387f.png">
Also get console log: AURemoteIO.cpp:1095:Initialize: failed: -66635 (enable 3, outf< 1 ch,  48000 Hz, Int16> inf< 1 ch,  48000 Hz, Int16>)

**Comment by Vladimirmlnkv** [comment]
@arjun-kava could you check this issue again, please?

**Comment by arjun-kava** [comment]
Hey, @Vladimirmlnkv We took it on a priority and trying to resolve it as soon as possible.

**Comment by Vladimirmlnkv** [comment]
There's also crash somewhere inside the library:
Fatal error: Attempted to read an unowned reference but object 0x282cca340 was already deallocated

When method self?.meeting?.end() called.

**Comment by evstratbg** [comment]
faced the same issue

**Comment by Vladimirmlnkv** [comment]
@arjun-kava hey, any updates on this issue? Maybe some estimates when it might be fixed?

**Comment by ahmedbhesaniya97** [comment]
Hey @Vladimirmlnkv 
We are on it and you might expect the resolution in few days🤞 .

**Comment by ahmedbhesaniya97** [comment]
Hey @Vladimirmlnkv @evstratbg,
We have made changes regarding leave crash.
Can you help us to give feedback by updating pod file in this example project or in your project.

**podfile :** 
```
pod 'VideoSDKRTC', :git => 'https://github.com/videosdk-live/videosdk-rtc-ios-sdk.git', :branch => 'beta-leave-crash'
```

**Screen Shot :**
<img width="898" alt="Screenshot 2022-06-23 at 12 50 25 PM" src="https://user-images.githubusercontent.com/65531261/175244068-c98df372-bba7-42eb-868d-51857b884168.png">


Thank you.

**Comment by Vladimirmlnkv** [comment]
@ahmedbhesaniya97 
i've got the crash with onowned ref in this new version, after i leave meating. Crash happens in the app, where i call meeting.leave(). Second app doesn't crash. 

I see that you added more logs to library, that's nice. Here's what i've got

`<=== acknowledgements Done
["data": {
    id = "b6f01cbe-807a-4d30-b49e-2228b153b83e";
}, "id": 973235, "ok": 1, "response": 1]
===>
<=== acknowledgements Done
["ok": 1, "response": 1, "id": 131284, "data": {
    id = "ac065db2-b2fa-4971-babb-9c414a7c18f2";
}]
===>
2022-06-23 12:47:13.615495+0400 u3Client[41750:3087103] fopen failed for data file: errno = 2 (No such file or directory)
2022-06-23 12:47:13.615620+0400 u3Client[41750:3087103] Errors found! Invalidating cache...
<=== acknowledgements Done
["response": 1, "ok": 1, "data": {
}, "id": 464315]
===>
2022-06-23 12:47:14.168023+0400 u3Client[41750:3089636] [aurioc]            AURemoteIO.cpp:1128  failed: -66635 (enable 3, outf< 1 ch,  48000 Hz, Int16> inf< 1 ch,  48000 Hz, Int16>)
activeSpeaker
activeSpeaker
Producer::onTransportClose
Producer::onTransportClose
completed
<====== Optional("0fde8912-5ca4-4f1a-9a71-e52555ca3ea1")
Optional("completed")
Consumer::onTransportClose Optional(<Consumer: 0x2803153a0>)
Consumer::onTransportClose Optional(<Consumer: 0x280312940>)
======>
VideoCoordinator deinit
VideoView Controller deinit
VideoView Model deinit
Fatal error: Attempted to read an unowned reference but object 0x2826bd5c0 was already deallocated`

**Comment by ahmedbhesaniya97** [comment]
Hey @Vladimirmlnkv,
Do couple of test at your side and let us know the other bug or crashes with reproducible steps.

**Comment by Vladimirmlnkv** [comment]
@ahmedbhesaniya97 
I've tested it multiple times, i've got crashes in 100% cases.
1. Crash when user leaves meeting (meeting.leave()) . (Details in my last message)
2. Crash when user ends meeting (meeting.end()). In this case crash happens in both apps. First app(the app where meeting.end() called) gets the same crash as in first case. Second app gets:
`Terminating app due to uncaught exception 'RuntimeException', reason: 'RecvTransport closed'
*** First throw call stack:
(0x19537b928 0x1a9118480 0x106878d74 0x1068b0dd4 0x105fcca38 0x105fd79e8 0x105fd7938 0x105fd7c7c 0x1966afd20 0x1952fb7a8 0x1952fb3a8 0x1952fa87c 0x1952f4bb4 0x1952f3ed0 0x1aba3d570 0x197c212d0 0x197c2684c 0x1a845287c 0x100e96a90 0x100e96a18 0x100e971a8 0x194fd2140)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'RuntimeException', reason: 'RecvTransport closed'
terminating with uncaught exception of type NSException`

**Comment by ahmedbhesaniya97** [comment]
Hi @Vladimirmlnkv,
Can you update pod file and let us know your feedback for the same.

**podfile :** 
```
pod 'VideoSDKRTC', :git => 'https://github.com/videosdk-live/videosdk-rtc-ios-sdk.git', :branch => 'leave-crash'
```

**Comment by Vladimirmlnkv** [comment]
@ahmedbhesaniya97 
Yes, it's the same for leaving meeting, for ending - i got new crash

When i leave meeting, i get crash:
Fatal error: Attempted to read an unowned reference but object 0x283846400 was already deallocated

When i end meeting, i get crash:
u3Client(55271,0x106ec4580) malloc: *** error for object 0x16d5f97d0: pointer being freed was not allocated
u3Client(55271,0x106ec4580) malloc: *** set a breakpoint in malloc_error_break to debug.

For unowned reference crash i suggest you search "unowned" word in project, and replace it all with [weak] capture, and safe unwrap values, no force unwraps. It seems like easy and obvious fix for me.

About end crash - i can't suggest anything, since i don't have access to your codebase.

**Comment by ahmedbhesaniya97** [comment]
Hi @Vladimirmlnkv,
Can you join our discord channel (https://discord.gg/8dzptZHS) for better and fast communication.

**Comment by Vladimirmlnkv** [comment]
I am using it already.
My account there: zhizhig galnash#9944

**Comment by arjun-kava** [comment]
This has been resolved in newer versions.
