### ISSUE TITLE
iOS project doesnt complile

### ISSUE THREAD

**Issue by rgustavsson** [videosdk-live/videosdk-rtc-ios-sdk-example#19]
Wasn't able to get the iOS project up and running. 

<img width="1159" alt="Screenshot 2023-09-09 at 01 24 10" src="https://github.com/videosdk-live/videosdk-rtc-ios-sdk-example/assets/4477604/5f35db74-ae8c-47cc-8cdc-44ea523b5296">

**Comment by ParthAsodariya** [comment]
Hey @rgustavsson, can you please try after executing below commands `pod update` & `pod repo update`.
