### ISSUE TITLE
Implimation in VidoSDk - RTC - IOS 

### ISSUE THREAD

**Issue by sagar1993007** [videosdk-live/videosdk-rtc-ios-sdk-example#2]
I am using into my existing code inside that already using the Objective-C libraries, So that project using **Bridging-Header.h** file.

Install pod provided into project.
`pod 'VideoSDKRTC', :git => 'https://github.com/videosdk-live/videosdk-rtc-ios-sdk.git'`

Simple Build and run project and fire following error.

```
error: using bridging headers with module interfaces is unsupported
Command CompileSwiftSources failed with a nonzero exit code
```
If remove pod  of file **pod 'VideoSDKRTC', :git => 'https://github.com/videosdk-live/videosdk-rtc-ios-sdk.git** it's working properly.

I am using **swift version 5** and Xcode version **13.1**

**Comment by imnimit** [comment]
@sagar1993007 
I found a solution to your problem.

in your Project Level & Target level **Build Settings** tab, open the **Build** Options menu. And then set **Build Libraries for Distribution** option to **No**.


![solution](https://user-images.githubusercontent.com/708425/141645433-6ced9b75-0695-4aed-9550-71d89b11aac0.png)
